/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gscencode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(62c0a17686b3c462993ecfed99ffbd1b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mixalot/gscencode.h>
// pydoc.h is automatically generated in the build directory
#include <gscencode_pydoc.h>

void bind_gscencode(py::module& m)
{

    using gscencode    = ::gr::mixalot::gscencode;


    py::class_<gscencode, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<gscencode>>(m, "gscencode", D(gscencode))

        .def(py::init(&gscencode::make),
           py::arg("type") = 0,
           py::arg("capcode") = 0,
           py::arg("message") = "",
           py::arg("symrate") = 38400,
           D(gscencode,make)
        )
        



        ;




}








